import { FC } from 'react';
import { FormElementTypes, FormGroupsTypes } from '../../store/formElements/types';
import {
  BadgeFormElement,
  ButtonFormElement,
  CardFormElement,
  CardWithBarChart,
  CheckboxFormElement,
  ComboBoxFormElement,
  CustomCards,
  CustomRectElement,
  Dashboard,
  DataTimeFormElement,
  DatePickerFormElement,
  ExpertiseForm,
  FooterWithSwitch,
  FormWithTwoColumns,
  HeaderCognitiveGeologist,
  HeaderWithBreadcrumbs,
  HeaderWithStatus,
  InformerFormElement,
  LayoutFormElement,
  ListFormElement,
  PlaceholderFormElement,
  ProjectGrid,
  RadioButtonFormElement,
  SelectFormElement,
  SimpleForm,
  SwitchFormElement,
  Table,
  TabsFormElement,
  TextFieldFormElement,
  WizardForm,
} from '../Elements';
import { CustomTextElement } from '../Elements/CustomTextElement/CustomTextElement';

export const FormGroupsDict: Record<FormGroupsTypes | FormElementTypes, FC<any>> = {
  Layout: LayoutFormElement,
  Button: ButtonFormElement,
  Badge: BadgeFormElement,
  Card: CardFormElement,
  Checkbox: CheckboxFormElement,
  HeaderWithBreadcrumbs: HeaderWithBreadcrumbs,
  HeaderWithStatus: HeaderWithStatus,
  HeaderCognitiveGeologist: HeaderCognitiveGeologist,
  Informer: InformerFormElement,
  Tabs: TabsFormElement,
  Text: TextFieldFormElement,
  TextField: TextFieldFormElement,
  Placeholder: PlaceholderFormElement,
  CardWithBarChart: CardWithBarChart,
  ProjectGrid: ProjectGrid,
  CustomCards: CustomCards,
  Dashboard: Dashboard,
  SimpleForm: SimpleForm,
  WizardForm: WizardForm,
  FooterWithSwitch: FooterWithSwitch,
  FormWithTwoColumns: FormWithTwoColumns,
  Table: Table,
  List: ListFormElement,
  RadioButton: RadioButtonFormElement,
  Switch: SwitchFormElement,
  DatePicker: DatePickerFormElement,
  SelectForm: SelectFormElement,
  ComboBox: ComboBoxFormElement,
  DataTime: DataTimeFormElement,
  ExpertiseForm: ExpertiseForm,
  CustomRect: CustomRectElement,
  CustomText: CustomTextElement,
};
