import { FC } from 'react'
import { FormElementTypes, FormGroupsTypes } from '../../store/formElements/types'
import {
  BadgeFormElement,
  ButtonFormElement,
  CardFormElement,
  CheckboxFormElement,
  HeaderWithBreadcrumbs,
  HeaderWithStatus,
  InformerFormElement,
  ProjectGrid,
  TabsFormElement,
  TextFieldFormElement,
  PlaceholderFormElement,
  CardWithBarChart,
  HeaderCognitiveGeologist,
  Dashboard,
  CustomCards,
  LayoutFormElement,
  SimpleForm,
  WizardForm,
  SimpleForm2,
} from '../Elements'

export const FormGroupsDict: Record<FormGroupsTypes | FormElementTypes, FC<any>> = {
  Layout: LayoutFormElement,
  Button: ButtonFormElement,
  Badge: BadgeFormElement,
  Card: CardFormElement,
  Checkbox: CheckboxFormElement,
  HeaderWithBreadcrumbs: HeaderWithBreadcrumbs,
  HeaderWithStatus: HeaderWithStatus,
  HeaderCognitiveGeologist: HeaderCognitiveGeologist,
  Informer: InformerFormElement,
  Tabs: TabsFormElement,
  Text: TextFieldFormElement,
  TextField: TextFieldFormElement,
  Placeholder: PlaceholderFormElement,
  CardWithBarChart: CardWithBarChart,
  ProjectGrid: ProjectGrid,
  CustomCards: CustomCards,
  Dashboard: Dashboard,
  SimpleForm: SimpleForm,
  WizardForm: WizardForm,
  SimpleForm2: SimpleForm2,
}
