export type {
  AddElementsWithInstancesPayload,
  AddNewElementPayload,
  ReorderPayload,
  SaveNewProject,
  UpdateBaseComponentPayload,
} from './actions'
export {
  addBaseComponent,
  addNewPage,
  addNewView,
  changeActivePage,
  changePageName,
  clearSameInstanceIds,
  copyFormElementLink,
  deletePage,
  deleteView,
  insertNewElements,
  loadProjectFromFile,
  loadProjectFromStorage,
  reorderFormElement,
  saveBaseComponent,
  saveProjectToFile,
  saveProjectToHTML,
  setDraggableElement,
  setInstanceProps,
  setSameElementsIdsById,
  setSelectedView,
  setViewLabel,
  setViewToCopyId,
  updateBaseComponentAction,
  updateOrders,
} from './actions'
export { formConstructorReducer, formConstructorSlice } from './formElementsSlice'
export {
  elementToCopyIdSelector,
  formInstancePropsSelector,
  formInstanceSelector,
  formInstancesSelector,
  getAllFormElements,
  getElementById,
  getElementsOnLayer,
  getFormConstructor,
  getFormElAsMap,
  getInstanceProps,
  getPages,
  getSelectedPageId,
  getSelectedPageName,
  getSelectedView,
  getSelectedViewPropsSelector,
  getSiblingsCount,
  getViewInfoDict,
  getViewInfoLabelByIdSelector,
  getViewInfosByIds,
  sameInstanceElementsIdsSelector,
} from './selectors'
