import { IconPropSize, IconPropView } from '@consta/uikit/Icon'
import { iconNames } from '../../../../store/formElements/iconTypes'

export const sizes: IconPropSize[] = [
  'm',
  's',
  'l',
  'xs',
]
export const views: IconPropView[] = [
  'ghost',
  'brand',
  'disabled',
  'ghost',
  'link',
  'primary',
  'secondary',
  'success',
  'warning',
]

export const icons: iconNames[] = [
  // 'Icon3DMap',
  // 'IconAltitude',
  // 'IconAmplitudes',
  // 'IconAttribute',
  // 'IconAxisX',
  // 'IconAxisY',
  // 'IconAxisZ',
  // 'IconDepth',
  // 'IconDots',
  // 'IconFractureBlue',
  // 'IconFractureFolder',
  // 'IconFractureGreen',
  // 'IconFractureMultiple',
  // 'IconFractureOrange',
  // 'IconFrequency',
  // 'IconGis',
  // 'IconGisAttributes',
  // 'IconGisMultiple',
  // 'IconHorizonBlue',
  // 'IconHorizonFolderBlue',
  // 'IconHorizonFolderGreen',
  // 'IconHorizonFolderOrange',
  // 'IconHorizonGreen',
  // 'IconHorizonMultiple',
  // 'IconHorizonOrange',
  // 'IconInclinometry',
  // 'IconInterpretations',
  // 'IconIronMap',
  // 'IconLayerBlue',
  // 'IconLayerYellow',
  // 'IconLitology',
  // 'IconMaps',
  // 'IconMarkers',
  // 'IconMarkersBlue',
  // 'IconMarkersOrange',
  // 'IconMeasuredDepth',
  // 'IconOilSaturationMap',
  // 'IconPermeabilityMap',
  // 'IconPolygonBlue',
  // 'IconPolygonMultiple',
  // 'IconPolygonOrange',
  // 'IconPorosity',
  // 'IconPorosityMap',
  // 'IconPolygonPurple',
  // 'IconRigiss',
  // 'IconSaturation',
  // 'IconSeismic2D',
  // 'IconStratigraphy',
  // 'IconTraectoryBlue',
  // 'IconTraectoryOrange',
  // 'IconWellAttributes',
  // 'IconWellBlue',
  // 'IconWellFolder',
  // 'IconWellGreen',
  // 'IconWellOrange',
  // 'IconWells',
  // 'IconZoneBlue',
  // 'IconZoneOrange',
  'IconAlert',
  'IconHealth',
  'IconInfo',
  'IconQuestion',
  'IconRouble',
  'IconWarning',
  'IconAdd',
  'IconAddToComparison',
  'IconAllDone',
  'IconArrowLast',
  'IconArrowFirst',
  'IconArrowNext',
  'IconArrowPrevious',
  'IconArrowRedone',
  'IconArrowUndone',
  'IconCancel',
  'IconCheck',
  'IconClose',
  'IconCopy',
  'IconDownload',
  'IconDraggable',
  'IconEdit',
  'IconExit',
  'IconEye',
  'IconEyeClose',
  'IconInComparison',
  'IconIntroduction',
  'IconLoading',
  'IconOpenInNew',
  'IconPaste',
  'IconRemove',
  'IconRemoveFromComparison',
  'IconReply',
  'IconResize',
  'IconRestart',
  'IconRevert',
  'IconRoute',
  'IconShuffle',
  'IconSlide',
  'IconTrash',
  'IconUpload',
  'IconAlignBlocksRight',
  'IconAlignBlocksLeft',
  'IconCards',
  'IconCollapse',
  'IconExpand',
  'IconExpandWidthCorner',
  'IconExpandWidthSide',
  'IconFitToDefault',
  'IconGrouping',
  'IconLogicalElement',
  'IconMaxHeight',
  'IconMaxWidth',
  'IconNodeEnd',
  'IconNodeStart',
  'IconNodeStep',
  'IconNodes',
  'IconPanelBottom',
  'IconPanelLeft',
  'IconPanelRight',
  'IconPanelTop',
  'IconShape',
  'IconTable2',
  'IconAlignCenter',
  'IconAlignJustify',
  'IconAlignLeft',
  'IconAlignRight',
  'IconBold',
  'IconColorFill',
  'IconColorText',
  'IconColumns',
  'IconItalic',
  'IconList',
  'IconListNumbered',
  'IconQuote',
  'IconStrikethrough',
  'IconTable',
  'IconType',
  'IconUnderline',
]