export type { AvatarProps_Deprecated } from './deprecatedAvatar'
export type { AvatarGroupProps_Deprecated } from './deprecatedAvatarGroups'
export type { BadgeProps_Deprecated } from './deprecatedBadge'
export type { BaseComponentToSave_Deprecated } from './deprecatedBaseComponent'
export type { BreadcrumbProps_Deprecated } from './deprecatedBreadCrumbs'
export type { ButtonProps_Deprecated } from './deprecatedButtonTypes'
export type { CardProps_Deprecated } from './deprecatedCard'
export type { CheckboxProps_Deprecated } from './deprecatedCheckbox'
export type {
  ChoiceGroupProps_Deprecated,
  MultipleChoiceGroupProps_Deprecated,
} from './deprecatedChoiceGroup'
export type { ComboboxProps_Deprecated } from './deprecatedComboBox'
export type { DatePickerProps_Deprecated } from './deprecatedDatePicker'
export type { DateTimeProps_Deprecated } from './deprecatedDateTimeProps'
export type { EChartProps_Deprecated } from './deprecatedEcharts'
export type { IconProps_Deprecated } from './deprecatedIcon'
export type { InformerElementProps_Deprecated } from './deprecatedInformer'
export type { LayoutElementPropsStyles_Deprecated } from './deprecatedLayout'
export type { ListProps_Deprecated } from './deprecatedList'
export type { RadioButtonProps_Deprecated } from './deprecatedRadioButtonProps'
export type { SelectProps_Deprecated, SelectStyles_Deprecated } from './deprecatedSelectProps'
export type { SwitchProps_Deprecated } from './deprecatedSwitch'
export type { TabsProps_Deprecated } from './deprecatedTabs'
export type { TagProps_Deprecated } from './deprecatedTags'
export type { TextProps_Deprecated } from './deprecatedText'
export type { TextFieldProps_Deprecated } from './deprecatedTextField'
export type { UserProps_Deprecated } from './deprecatedUserProps'
export type { FormConstructorToSave_Deprecated } from './deptrecatedFormConstructor'
