export const spacingStyles: Record<string, string> = {
  // Отступы справа
  'p-r-3xs': 'padding-right: var(--space-3xs);',
  'p-r-2xs': 'padding-right: var(--space-2xs);',
  'p-r-xs': 'padding-right: var(--space-xs);',
  'p-r-s': 'padding-right: var(--space-s);',
  'p-r-m': 'padding-right: var(--space-m);',
  'p-r-l': 'padding-right: var(--space-l);',
  'p-r-xl': 'padding-right: var(--space-xl);',
  'p-r-2xl': 'padding-right: var(--space-2xl);',
  'p-r-3xl': 'padding-right: var(--space-3xl);',
  'p-r-4xl': 'padding-right: var(--space-4xl);',
  'p-r-5xl': 'padding-right: var(--space-5xl);',
  'p-r-6xl': 'padding-right: var(--space-6xl);',

  // Отступы слева
  'p-l-3xs': 'padding-left: var(--space-3xs);',
  'p-l-2xs': 'padding-left: var(--space-2xs);',
  'p-l-xs': 'padding-left: var(--space-xs);',
  'p-l-s': 'padding-left: var(--space-s);',
  'p-l-m': 'padding-left: var(--space-m);',
  'p-l-l': 'padding-left: var(--space-l);',
  'p-l-xl': 'padding-left: var(--space-xl);',
  'p-l-2xl': 'padding-left: var(--space-2xl);',
  'p-l-3xl': 'padding-left: var(--space-3xl);',
  'p-l-4xl': 'padding-left: var(--space-4xl);',
  'p-l-5xl': 'padding-left: var(--space-5xl);',
  'p-l-6xl': 'padding-left: var(--space-6xl);',

  // Отступы сверху
  'p-t-3xs': 'padding-top: var(--space-3xs);',
  'p-t-2xs': 'padding-top: var(--space-2xs);',
  'p-t-xs': 'padding-top: var(--space-xs);',
  'p-t-s': 'padding-top: var(--space-s);',
  'p-t-m': 'padding-top: var(--space-m);',
  'p-t-l': 'padding-top: var(--space-l);',
  'p-t-xl': 'padding-top: var(--space-xl);',
  'p-t-2xl': 'padding-top: var(--space-2xl);',
  'p-t-3xl': 'padding-top: var(--space-3xl);',
  'p-t-4xl': 'padding-top: var(--space-4xl);',
  'p-t-5xl': 'padding-top: var(--space-5xl);',
  'p-t-6xl': 'padding-top: var(--space-6xl);',

  // Отступы снизу
  'p-b-3xs': 'padding-bottom: var(--space-3xs);',
  'p-b-2xs': 'padding-bottom: var(--space-2xs);',
  'p-b-xs': 'padding-bottom: var(--space-xs);',
  'p-b-s': 'padding-bottom: var(--space-s);',
  'p-b-m': 'padding-bottom: var(--space-m);',
  'p-b-l': 'padding-bottom: var(--space-l);',
  'p-b-xl': 'padding-bottom: var(--space-xl);',
  'p-b-2xl': 'padding-bottom: var(--space-2xl);',
  'p-b-3xl': 'padding-bottom: var(--space-3xl);',
  'p-b-4xl': 'padding-bottom: var(--space-4xl);',
  'p-b-5xl': 'padding-bottom: var(--space-5xl);',
  'p-b-6xl': 'padding-bottom: var(--space-6xl);',

  // Отступы справа (margin)
  'm-r-3xs': 'margin-right: var(--space-3xs);',
  'm-r-2xs': 'margin-right: var(--space-2xs);',
  'm-r-xs': 'margin-right: var(--space-xs);',
  'm-r-s': 'margin-right: var(--space-s);',
  'm-r-m': 'margin-right: var(--space-m);',
  'm-r-l': 'margin-right: var(--space-l);',
  'm-r-xl': 'margin-right: var(--space-xl);',
  'm-r-2xl': 'margin-right: var(--space-2xl);',
  'm-r-3xl': 'margin-right: var(--space-3xl);',
  'm-r-4xl': 'margin-right: var(--space-4xl);',
  'm-r-5xl': 'margin-right: var(--space-5xl);',
  'm-r-6xl': 'margin-right: var(--space-6xl);',

  // Отступы слева (margin)
  'm-l-3xs': 'margin-left: var(--space-3xs);',
  'm-l-2xs': 'margin-left: var(--space-2xs);',
  'm-l-xs': 'margin-left: var(--space-xs);',
  'm-l-s': 'margin-left: var(--space-s);',
  'm-l-m': 'margin-left: var(--space-m);',
  'm-l-l': 'margin-left: var(--space-l);',
  'm-l-xl': 'margin-left: var(--space-xl);',
  'm-l-2xl': 'margin-left: var(--space-2xl);',
  'm-l-3xl': 'margin-left: var(--space-3xl);',
  'm-l-4xl': 'margin-left: var(--space-4xl);',
  'm-l-5xl': 'margin-left: var(--space-5xl);',
  'm-l-6xl': 'margin-left: var(--space-6xl);',

  // Отступы сверху (margin)
  'm-t-3xs': 'margin-top: var(--space-3xs);',
  'm-t-2xs': 'margin-top: var(--space-2xs);',
  'm-t-xs': 'margin-top: var(--space-xs);',
  'm-t-s': 'margin-top: var(--space-s);',
  'm-t-m': 'margin-top: var(--space-m);',
  'm-t-l': 'margin-top: var(--space-l);',
  'm-t-xl': 'margin-top: var(--space-xl);',
  'm-t-2xl': 'margin-top: var(--space-2xl);',
  'm-t-3xl': 'margin-top: var(--space-3xl);',
  'm-t-4xl': 'margin-top: var(--space-4xl);',
  'm-t-5xl': 'margin-top: var(--space-5xl);',
  'm-t-6xl': 'margin-top: var(--space-6xl);',

  // Отступы снизу (margin)
  'm-b-3xs': 'margin-bottom: var(--space-3xs);',
  'm-b-2xs': 'margin-bottom: var(--space-2xs);',
  'm-b-xs': 'margin-bottom: var(--space-xs);',
  'm-b-s': 'margin-bottom: var(--space-s);',
  'm-b-m': 'margin-bottom: var(--space-m);',
  'm-b-l': 'margin-bottom: var(--space-l);',
  'm-b-xl': 'margin-bottom: var(--space-xl);',
  'm-b-2xl': 'margin-bottom: var(--space-2xl);',
  'm-b-3xl': 'margin-bottom: var(--space-3xl);',
  'm-b-4xl': 'margin-bottom: var(--space-4xl);',
  'm-b-5xl': 'margin-bottom: var(--space-5xl);',
  'm-b-6xl': 'margin-bottom: var(--space-6xl);',
}
