export { addNewFormInstance } from './addNewInstance'
export { changeElementLinkCount } from './changeElementLinkCount'
export type { ChangeElementLinkCountPayload, LinkCountType } from './payloads'
export { setSameInstanceElementsIds } from './setSameInstanceElementIds'
export { updateFormInstance } from './updateFormInstance'
