import type { FC } from 'react'

import type { FormElementTypes, FormGroupsTypes } from '../coreTypes'

import {
  AvatarFormElement,
  AvatarGroupFormElement,
  BadgeFormElement,
  BreadcrumbsFormElement,
  ButtonFormElement,
  CardFormElement,
  CheckboxFormElement,
  ChoiceGroupFormElement,
  ComboBoxFormElement,
  DataTimeFormElement,
  DatePickerFormElement,
  EChartFormElement,
  IconFormElement,
  InformerFormElement,
  LayoutFormElement,
  ListFormElement,
  RadioButtonFormElement,
  SelectFormElement,
  SwitchFormElement,
  TabsFormElement,
  TagFormElement,
  TextFieldFormElement,
  TextFormElement,
  UserFormElement,
} from './Elements'

export const FormGroupsDict: Record<FormGroupsTypes | FormElementTypes, FC<any>> = {
  Avatar: AvatarFormElement,
  AvatarGroup: AvatarGroupFormElement,
  Layout: LayoutFormElement,
  Button: ButtonFormElement,
  Badge: BadgeFormElement,
  EChart: EChartFormElement,
  Card: CardFormElement,
  Checkbox: CheckboxFormElement,
  Informer: InformerFormElement,
  Tabs: TabsFormElement,
  Text: TextFormElement,
  TextField: TextFieldFormElement,
  List: ListFormElement,
  RadioButton: RadioButtonFormElement,
  Switch: SwitchFormElement,
  DatePicker: DatePickerFormElement,
  SelectForm: SelectFormElement,
  ComboBox: ComboBoxFormElement,
  DataTime: DataTimeFormElement,
  BreadcrumbsFormElement,
  User: UserFormElement,
  Icon: IconFormElement,
  Tag: TagFormElement,
  ChoiceGroup: ChoiceGroupFormElement,
}
