import type { FC } from 'react'

import type { FormElementTypes, FormGroupsTypes } from '../coreTypes'

import {
  AvatarFormElement,
  AvatarGroupFormElement,
  BadgeFormElement,
  BreadcrumbsFormElement,
  ButtonActionModal,
  ButtonFormElement,
  CardFormElement,
  CardWithBarChart,
  CheckboxFormElement,
  ChoiceGroupFormElement,
  ComboBoxFormElement,
  Dashboard,
  DataTimeFormElement,
  DatePickerFormElement,
  FooterWithSwitch,
  IconFormElement,
  InformerFormElement,
  LayoutFormElement,
  ListFormElement,
  PlaceholderFormElement,
  PrototypeRectangleElement,
  PrototypeTextElement,
  RadioButtonFormElement,
  SelectFormElement,
  SimpleForm,
  SwitchFormElement,
  Table,
  TabsFormElement,
  TagFormElement,
  TextFieldFormElement,
  TextFormElement,
  UserFormElement,
  WizardForm,
} from './Elements'

export const FormGroupsDict: Record<FormGroupsTypes | FormElementTypes, FC<any>> = {
  Avatar: AvatarFormElement,
  AvatarGroup: AvatarGroupFormElement,
  Layout: LayoutFormElement,
  Button: ButtonFormElement,
  Badge: BadgeFormElement,
  Card: CardFormElement,
  Checkbox: CheckboxFormElement,
  Informer: InformerFormElement,
  Tabs: TabsFormElement,
  Text: TextFormElement,
  TextField: TextFieldFormElement,
  Placeholder: PlaceholderFormElement,
  CardWithBarChart,
  Dashboard,
  SimpleForm,
  WizardForm,
  FooterWithSwitch,
  Table,
  List: ListFormElement,
  RadioButton: RadioButtonFormElement,
  Switch: SwitchFormElement,
  DatePicker: DatePickerFormElement,
  SelectForm: SelectFormElement,
  ComboBox: ComboBoxFormElement,
  DataTime: DataTimeFormElement,
  PrototypeTextElement,
  PrototypeRectangleElement,
  BreadcrumbsFormElement,
  User: UserFormElement,
  Icon: IconFormElement,
  ButtonModal: ButtonActionModal,
  Tag: TagFormElement,
  ChoiceGroup: ChoiceGroupFormElement,
}
