export { addNewElement } from './addNewElement'
export { deleteElement } from './deleteElement'
export { togglePanelByHotKey } from './togglePanelsByHotKey'
export { loadProjectFromStorage } from './loadProjectFromStorage'
export { saveProjectToMemmoryStorage } from './saveProjectToMemmoryStorage'
export { saveProjectToFile } from './saveProjectToFile'
export { setSelectedElement } from './setSelectedElement'
export { addNewPage } from './addNewPage'
export { changeActivePage } from './changeActivePage'
export { closePage } from './closePage'

